name: release

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
        php-versions: ['7.2', '7.3', '7.4']
    steps:
      - uses: actions/checkout@v2

      - name: Install PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Test with PHPUnit, generate code coverage
        run: php ./vendor/phpunit/phpunit/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1