name: staging

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ['7.2', '7.3', '7.4']

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Test with PHPUnit, generate code coverage
        run: php ./vendor/phpunit/phpunit/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1